<?php

/** 
 * Container to display the Listing front end by intitializing a Vue app
 * with the appropriate components specified in the app folder
 * 
 * @since      0.1.0
 * @author    Igor Honhoff
 */
class FG_listings_app
{
    /* Hold the class instance. */
    private static $instance = null;
    
    /**
     * The object is created from within the class itself
     * only if the class has no instance.
     *
     * @return FG_listings_app
     **/
    public static function getInstance()
        {
            if (self::$instance == null)
            {
            self::$instance = new FG_listings_app();
            }
        
            return self::$instance;
        }

    /**
     * The constructor
     **/
    private function __construct() {
        add_shortcode( 'listings', [ $this, 'add_shortcode' ] );
        add_action( 'wp_enqueue_scripts', [ $this, 'register_js' ] );
    }

    /**
     * Add a listings shortcode that initializes the listings Vue app
     * 
     * @return String The container div for the app
     */
    public function add_shortcode( $atts ) {
        // The shortcode's type parameter sets the Vue component to be loaded.
        $atts = shortcode_atts( [
            'type'  => 'ServiceProviders',
        ], $atts, 'listings' );

        // make custom data available to the Vue app
        wp_localize_script(
            'listings_vendors',
            'listingsWpData',
            [
                'assetsUri' => dirname( __DIR__ ) . '/assets',
                'rest_url'  => untrailingslashit( esc_url_raw( rest_url() ) ),
                'app_path'  => get_permalink(),
                'nonce'     => wp_create_nonce( 'wp_rest' ),
                'userid'    => get_current_user_id(),
                'type'      => $atts['type'],
            ]
            );
        
        // enqueue the Vue app script with localized data.
        wp_enqueue_script( 'listings_app' );
        
        // Enqueue Font Awesome
        wp_enqueue_style(
            'font-awesome-free',
            'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css'
        );

        $html_atts = ' ';

        foreach ($atts as $attr => $val) {
            $html_atts .= $attr . '="' . $val . '" ';
        }

        return '<div id="fg-listings-app"></div>';
    }

    /**
     * Register the necessary script files in the compiled Vue app
     */
    public function register_js()
    {
        // If app build exists, use pre-built javascript, otherwise use vue dev server.
        $app_dir = dirname( __DIR__ ) . '/app/dist/js';
        if ( file_exists( $app_dir ) ) {
            $app_url = plugin_dir_url( $app_dir );
        } else {
            $site_url = parse_url( get_site_url() );
            $app_url = $site_url['scheme'] . '://' . $site_url['host'] . ':8080/';
        }

        // register the Vue vendors script.
		wp_register_script( // the app build script generated by Webpack.
			'listings_vendors',
            $app_url . 'js/chunk-vendors.js',
			[],
			null,
			true
		);

        // register the Vue app script.
		wp_register_script( // the app build script generated by Webpack.
			'listings_app',
            $app_url . 'js/app.js',
			[ 'listings_vendors' ],
			null,
			true
		);
           
    }

}

FG_listings_app::getInstance();
